# License: GNU Affero General Public License v3 or later
# A copy of GNU AGPL v3 should have been included in this software package in LICENSE.txt.

""" A module for comparing clusters """

import os
from typing import Any, Dict, List, Optional

from antismash.common import path
from antismash.config import ConfigType, get_config
from antismash.config.args import ModuleArgs
from antismash.common.secmet import Record

# TODO don't reference CB directly
from antismash.modules.clusterblast.core import check_clusterblast_files


from .results import ClusterCompareResults
from .analysis import run
from .html_output import generate_html, will_handle

NAME = "cluster-compare"
SHORT_DESCRIPTION = "cluster comparison"


def get_arguments() -> ModuleArgs:
    """ Constucts module arguments
    """
    args = ModuleArgs("Advanced options", "clustercompare")  # TODO: change to False, allow custom data, etc
    args.add_analysis_toggle("clustercompare",
                             dest='clustercompare',
                             action='store_true',
                             default=False,
                             help="TODO")   # TODO
    return args


def check_options(_options: ConfigType) -> List[str]:
    """ Check the options of this module for any conflicting or invalid values.

        Arguments:
            options: the options parsed by the main entry point as an
                     antismash.Config object

        Returns:
            a list of strings describing any errors, if they exist
    """
    return []


def prepare_data(logging_only: bool = False) -> List[str]:
    """ Ensures packaged data is fully prepared

        Arguments:
            logging_only: whether to return error messages instead of raising exceptions

        Returns:
            a list of error messages (only if logging_only is True)
    """
    failure_messages = []
    data_dir = path.get_full_path(__file__, "data")
    # TODO handle custom data dir as additional or replacement
    cluster_defs = os.path.join(data_dir, 'data.json')
    protein_seqs = os.path.join(data_dir, "proteins.fasta")
    db_file = os.path.join(data_dir, "proteins.dmnd")

    failure_messages.extend(check_clusterblast_files(cluster_defs, protein_seqs, db_file, logging_only=logging_only))
    open(db_file)

    return failure_messages


def check_prereqs(options: ConfigType) -> List[str]:
    "Check if all required applications are around"

    failure_messages = []
    for binary_name in ["diamond"]:
        if binary_name not in options.executables:
            failure_messages.append("Failed to locate file: %r" % binary_name)

    if "diamond" not in get_config().executables:
        failure_messages.append("cannot check cluster_compare databases, no diamond executable present")
        return failure_messages

    failure_messages.extend(prepare_data(logging_only=True))
    return failure_messages


def is_enabled(options: ConfigType) -> bool:
    """ Returns True if the module is enabled by the given options """
    return options.clustercompare


def regenerate_previous_results(previous: Dict[str, Any], record: Record,
                                _options: ConfigType) -> Optional[ClusterCompareResults]:
    """ Rebuild the previous run results from a JSON object into this module's
        python results class. If the current options are incompatible with the
        previous results, None should be returned.

        Arguments:
            previous: the previous results as a dictionary
            record: the Record that was used to generate the previous results
            options: an antismash.Config object
    """
    import logging; logging.critical("discarding previous cluster-compare results")  # TODO
    return ClusterCompareResults.from_json(previous, record)


def run_on_record(record: Record, results: Optional[ClusterCompareResults], _options: ConfigType) -> ClusterCompareResults:
    """ Run this module's analysis section on the given record or use the
        previous results.

        Arguments:
            record: the Record instance to analyse
            results: the previous results as generated by regenerate_previous_results()
            options: an antismash.Config object

        Returns:
            this module's results as a subclass of
                antismash.common.module_results.ModuleResults
    """
    if results:
        return results
    return run(record)
